##################################################################################
# Details ServiceExport
##################################################################################
apiVersion: networking.kubeslice.io/v1beta1
kind: ServiceExport
metadata:
  name: details
  namespace: bookinfo
spec:
  slice: bookinfo-slice  #Replace Slice Name
  selector:
    matchLabels:
      app: details
  ingressEnabled: true
  ports:
  - name: http
    containerPort: 9080
    protocol: TCP
---
##################################################################################
# Reviews ServiceExport
##################################################################################
apiVersion: networking.kubeslice.io/v1beta1
kind: ServiceExport
metadata:
  name: reviews
  namespace: bookinfo
spec:
  slice: bookinfo-slice  #Replace Slice Name
  selector:
    matchLabels:
      app: reviews
  ingressEnabled: true
  ports:
  - name: http
    containerPort: 9080
    protocol: TCP
---
##################################################################################
# Ratings ServiceExport
##################################################################################
apiVersion: networking.kubeslice.io/v1beta1
kind: ServiceExport
metadata:
  name: ratings
  namespace: bookinfo
spec:
  slice: bookinfo-slice  #Replace Slice Name
  selector:
    matchLabels:
      app: ratings
  ingressEnabled: true
  ports:
  - name: http
    containerPort: 9080
    protocol: TCP
